import './globals.css'
import { Providers } from '../providers/providers'
import { Inter } from "next/font/google"

const inter = Inter({subsets: ["latin"]});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={`${inter.className} text-stone-950 bg-stone-100`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
